### ISSUE TITLE
No sound, error: "aplay: not found"

### ISSUE THREAD

**Issue by matteograsso** [MaxHalford/chime#18]
Hey there, I love chime! I'm having troubles running it on a remote server. This is what I get when I call `chime.info(sync=True, raise_error=True)`:

`RuntimeError: Command 'aplay /home/mgrasso/miniconda3/envs/pyphi/lib/python3.7/site-packages/themes/zelda/info.wav' returned non-zero exit status 127. stderr: /bin/sh: 1: aplay: not found
`

Any tips? Thanks in advance,
MG

**Comment by MaxHalford** [comment]
Hey, glad you like it!

I'm guessing you're on Linux, right? I believe you need to install `aplay`. Typically this is installed by default for most Linux setups, but maybe you're using a more barebones server that doesn't have a lot of default stuff installed.

**Comment by matteograsso** [comment]
Thanks a lot! Oddly enough I've pip installed aplay and chime, imported
both, and still get the same error. Could it be because I'm running the
jupyter notebook on a remote server without soundboard?

**Comment by MaxHalford** [comment]
I'm pretty sure that `aplay` isn't something you can pip install. It's a Linux package, so you should install it with `apt-get install aplay` or whatever package manager you're using on your Linux distro :)

**Comment by matteograsso** [comment]
I see, that should solve it, thanks for your help with something that goes
beyond chime.

Best,

Matteo

**Comment by BrokedTV** [comment]
Hey there!
I'm trying to use Chime on a remote server, i cannot hear any audo while connecting remotely, i tried to install 
apt-get install alsa-utils  (which should be aplay) but i still get no audio, any suggestion?
appreciated!

**Comment by MaxHalford** [comment]
Hello @BrokedTV! To be honest I've never tried making `chime` work on remote servers. So my answer right now is that I don't know. It looks rather involved from a quick search online. If you do solve this issue, it would be nice to add a note to the README.

**Comment by ywsyws** [comment]
As per chime 0.7.0, it says "Make it work with a remote machine." under "Things to do". So, I guess it is not going to work in remote for the moment.

https://pypi.org/project/chime/#i-cant-hear-anything-:~:text=Be%20creative!%20%F0%9F%91%A9%E2%80%8D%F0%9F%8E%A8-,Things%20to%20do,-Some%20mechanism%20to
